apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-addon-controller-ocyz
    app.kubernetes.io/part-of: governance-policy-addon-controller
  name: governance-policy-addon-controller-ocyz
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:2bf03a1503e99afbc95c8dc2fe27bc83148e7eae8b3152d21f89485790c937f5
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 8080
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 8080
        resources:
          limits:
            cpu: "1"
            memory: 512Mi
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
