apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: governance-policy-addon-controller-ocyz
    app.kubernetes.io/part-of: governance-policy-addon-controller
  name: governance-policy-addon-controller-ocyz
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: governance-policy-addon-controller-ocyz
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:e5abdf910b77605f9d0e8dae0777112547dfa435046d0ef926240deac27e9a7d
        imagePullPolicy: Always
        name: container-image
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
