apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-addon-controller-ocyz
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:56163cc8da0a7a08e52523ffe00511c04c36c5fc310e5d27889d72225e9c90d4
        name: container-image
        resources: {}
status: {}
