apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: governance-policy-addon-controller-ocyz
  namespace: red-hat-acm-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload@sha256:e5abdf910b77605f9d0e8dae0777112547dfa435046d0ef926240deac27e9a7d
        name: container-image
        resources: {}
status: {}
